experiment: 
  label: v1.T5_test
  seed: 0
  target: CATE # ATE / OPE #@TODO: Not used
  outcome: 'income'
  intervention: 'studies'
  intervention0: 'No studies'
  intervention1: 'Full-time studies'
  covariates: ['age', 'capital-net', 'hours-per-week', 'education-num', 'native-country', 
               'sex', 'race', 'education', 'workclass', 'occupation', 'marital-status', 
               'relationship', 'income_prev', 'studies_prev'] 

results:
  base_path: results/

selection: 
  type: random # grid/random
  n_iter: 1 # Used by random sampler
  folds: 5

data: 
  label: income
  path: samples/
  observational: income_scm.v1_default_n10000_T5_s0.pkl
  control: income_scm.v1_no_n10000_T5_s1.pkl # Should have a different seed than the observational! # Can be specified as None if the target is OPE
  target: income_scm.v1_full_n10000_T5_s1.pkl

estimators: 

  ipw-lr: 
    label: 'IPWEstimator (LR)'
    estimator: 'IPWEstimator'
    weighted: [False]
    base_estimator: ['lr']
    base_estimator__C: [0.01, 0.1, 1, 2, 10, 20, 100, 200, 1000]
